ui: display: prevent mismatched_lifetime_syntaxes compile warning
The missing lifetime annotation results in the build showing a warning
when compiled using the nightly toolchain:

>  error: lifetime flowing from input to output with different syntax can be confusing
>    --> src/ui/display.rs:147:19
>      |
>  147 |     pub fn rotate(&mut self) -> DisplayRotated {
>      |                   ^^^^^^^^^     -------------- the lifetime gets resolved as `'_`
>      |                   |
>      |                   this lifetime flows to the output
>      |
>      = note: `-D mismatched-lifetime-syntaxes` implied by `-D warnings`
>      = help: to override `-D warnings` add `#[allow(mismatched_lifetime_syntaxes)]`
>  help: one option is to remove the lifetime for references and use the anonymous lifetime for paths
>      |
>  147 |     pub fn rotate(&mut self) -> DisplayRotated<'_> {
>      |                                               ++++

Fix that by adding the suggested annotation.

Signed-off-by: Leonard Göhrs <l.goehrs@pengutronix.de>