tacd: replace instances of x % N == 0 with x.is_multiple_of(N)
This is inspired by a recently added clippy lint:

   error: manual implementation of `.is_multiple_of()`
     --> src/dut_power.rs:248:16
      |
  248 |             if N % 2 == 0 {
      |                ^^^^^^^^^^ help: replace with: `N.is_multiple_of(2)`
      |
      = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#manual_is_multiple_of
      = note: `-D clippy::manual-is-multiple-of` implied by `-D warnings`
      = help: to override `-D warnings` add `#[allow(clippy::manual_is_multiple_of)]`

  error: manual implementation of `.is_multiple_of()`
     --> src/ui/screens/diagnostics.rs:256:26
      |
  256 |                 let on = self.led_cycle_state % 2 != 0;
      |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: replace with: `!self.led_cycle_state.is_multiple_of(2)`
      |
      = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#manual_is_multiple_of

This change has become possible since we removed support for the rustc in
yocto walnascar, which did not have x.is_multiple_of(N).

Signed-off-by: Leonard Göhrs <l.goehrs@pengutronix.de>